### ISSUE TITLE
Rails 5 filterrific-spinner not processed by asset pipeline

### ISSUE THREAD

**Issue by olegantonyan** [jhund/filterrific#83]
rails 5.0.0.beta2

```
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( filterrific/filterrific-spinner.gif )` to `config/initializers/assets.rb` and restart your server
```

Without rendering the spinner or with `Rails.application.config.assets.precompile += %w( filterrific/filterrific-spinner.gif )` in initializer it works just fine

**Comment by Olaf1989** [comment]
It is caused by the sprockets-rails gem. Version 3.0.0 and higher are forcing the standards. Just set it to a lower version (2.3.3). **Source**:
[http://stackoverflow.com/questions/34344094/after-gem-update-test-fail-with-asset-was-not-declared-to-be-precompiled-in-pr](url)

**Comment by olegantonyan** [comment]
Thanks!

**Comment by jhund** [comment]
This has been fixed with 2.1.2 release

**Comment by McSlow** [comment]
Seems that it is still present:
```
Showing /app/app/views/wuapplicationinstances/_list.html.haml where line #4 raised:
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( filterrific/filterrific-spinner.gif )` to `config/initializers/assets.rb` and restart your server
```

/app $ bundle show filterrific
/gems/gems/filterrific-2.1.2

But this is on Rails 4.2
